name: ESLint
on:
  pull_request:
    branches:
      - "main"
    tags: [ v* ]
jobs:
  eslint:
    name: Run ESLint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v2
      - uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          eslint_flags: "./src"
          workdir: "./docs-web/src/main/webapp"
